---
- hosts: all
  gather_facts: true
  remote_user: benvon
  become: true
  become_user: root
  become_method: sudo
  
  tasks:
    - name: "Ubuntu and Raspian machines update everything"
      apt:
        upgrade: dist
        update_cache: yes
      when:
        - ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' or ansible_distribution == 'Raspian'
#      notify: 
#        - reboot

    - name: "CentOS machines update everything"
      yum:
        name: '*'
        state: latest
      when:
        - ansible_distribution == 'CentOS' 
#      notify: 
#        - reboot

    - name: "Fedora machines update everything"
      dnf:
        name: '*'
        state: latest
      when:
        - ansible_distribution == 'Fedora' 
#      notify: 
#        - reboot

    - name: "apt: Clean up after yourself..."
      apt:
        autoremove: yes
      when:
        - ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' or ansible_distribution == 'Raspian'
#      notify:
#        - reboot

    - name: "dnf: Clean up after yourself..."
      dnf:
        autoremove: yes
      when:
        - ansible_distribution == 'Fedora' 
#      notify:
#        - reboot


  handlers:
    - name: reboot
      command: /sbin/reboot
